### ISSUE TITLE
Possibility to skip some models

### ISSUE THREAD

**Issue by igeligel** [iiian/prisma-case-format#45]
Would like to have an option to disable the linter for some models.

Proposal:

```prisma
/* prisma-case-format-disable */

model Account {
  id                String  @id @default(cuid())
  userId            String 
  type              String
  provider          String
  providerAccountId String  
  refreshToken      String?
  accessToken       String? 
  expiresAt         Int?    
  tokenType         String? 
  scope             String?
  idToken           String?
  sessionState      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
/* prisma-case-format-enable */
```

I came across this issue when wanting to use next-auth

**Comment by iiian** [comment]
Hey @igeligel, thanks for the suggestion. What is `next-auth`, is that part of the `nextjs` ecosystem? If you don't mind me asking, what is the existing problem that you're facing, which these annotations would solve?

**Comment by dgellow** [comment]
Hi @iiian,

you're correct [next-auth](https://next-auth.js.org/getting-started/introduction) is part of the next.js ecosystem. It is a package that makes it fairly simple to setup authentication for a website. It supports various providers, and Prisma is one of them. You can check the provider documentation [here](https://authjs.dev/reference/adapter/prisma), the expected schema has strict requirements for casing, some fields of the generated Prisma client are expected to be snake_case (such as `token_type`, `expires_at`), while other need to be camelCase (`providerAccountId`, `userId`).

We faced the same issue as @igeligel, I've myself been bitten by the casing while cleaning up our DB schema. I now would like to rely on a tool such as `prisma-case-format` as a linter to ensure we use consistent names. But that would require to either be able to disable `prisma-case-format` for next-auth's models, or a way to specify (via comments?) the case to use for a specific column.

**Comment by iiian** [comment]
Got it, thanks for motivating the need--the problem makes sense to me now. Just commenting, seems like the disable feature is useful, and simultaneously the same could be achieved if just overrides for syntax expectations were allowed:
```prisma
// prisma-case-format:override
// --field-case=camel
// --map-field-case=snake
model GotchaNextAuthModel {
  // now fields are forced to format as camel, with snake @map anno's
  tokenType String @map('token_type')
  expiresAt String @map('expires_at')
}
// prisma-case-format:end-override
```

That way, `prisma-case-format` can enforce the case-convention deviation.

**Comment by iiian** [comment]
I like comments as the trigger, but we'll probably end up wanting to do a commandline arg as well, I'll have to think on that.

Ultimately, I think I hope to support this feature by the end of the year--is that soon enough?

**Comment by dgellow** [comment]
The override syntax is a neat idea, that would make it nicer to handle models that require a specific casing.

Looking at next-auth models, I would say that `Account` is the most problematic one, because it expects a mix of casing, that makes it a good test case to try out different strategies.

An idea would be to support override comments on the same line, in addition to an override block like the one you suggested.

```prisma

// 👇 set a default case for the model, for both the Prisma client and columns @map()  
//
// prisma-case-format:override(field-case=camel,map-field-case=snake)
model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
                                        // 👇 override some columns, only --field-case
  refresh_token      String?  @db.Text  // prisma-case-format:override(field-case=snake)
  access_token       String?  @db.Text  // prisma-case-format:override(field-case=snake)
  expires_at         Int?               // prisma-case-format:override(field-case=snake)
  token_type         String?            // prisma-case-format:override(field-case=snake)
  
  scope              String?
  id_token           String?  @db.Text  // prisma-case-format:override(field-case=snake)
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}
// prisma-case-format:end-override

```

Here the logic would be straight forward:

1. if a line starts with `prisma-case-format:override`, start an override block
2. if an inlined comment starts with `prisma-case-format:override`, override only for that specific line
3. if a line starts with `prisma-case-format:end-override`, stop the override block

I don't think something more complicated such as nested override blocks would make too much sense here, that wouldn't be too readable.

What do you think? I slightly changed your override syntax to make it simpler to use inlined, but that's just a suggestion and my personal preference 😄.

> Ultimately, I think I hope to support this feature by the end of the year--is that soon enough?

Oh for sure, yes!

**Comment by iiian** [comment]
Yep sounds good to me -- I guess we'll just have to say "it has to be the first part of a comment", because we're seizing control of the inline comment, which might clash with other functionality (why I'm generally opposed to adding control flags **directly** within the file, but in this case it seemed harmless as far as we were going with `disable`.

I'm almost wondering if there's not value in just creating a `--has-next-auth` flag, that applies a pre-defined set of case-conventions.

Are there any comments pushing back against `@vercel` doing this to y'all? Seems arbitrary and poorly published

**Comment by dgellow** [comment]
I had to look it up because I wasn't sure but it doesn't seem to be an official project made by Vercel: https://opencollective.com/nextauth. The package name sounds official but it is made by the community at large.

I'm myself not too familiar with Next.js and its community, I couldn't tell you if this schema weirdness is something people push back against or if it seen as normal. I literally learned about next-auth 2 days ago when doing changes to tables used by a Next.js application and broke signin/signup after renaming some specific columns of the next-auth Github provider (they aren't documented anywhere on next-auth website or GitHub repo, I only found out about it thanks to Prisma having really good error messages). So, not really a fan :)

> because we're seizing control of the inline comment, which might clash with other functionality put forth by prisma or other 3rd parties

Yes I agree, that's a fair point.

**Comment by dgellow** [comment]
I found [this comment](https://github.com/nextauthjs/next-auth/pull/8833#issuecomment-1763264623):

> Thanks, but this looks correct to me. NextAuth.js provided properties are camelCase while the ones based on the OAuth standard are following snake_case

**Comment by iiian** [comment]
I'll start with the inline `// prisma-case-format:disable ... // prisma-case-format:disable-end` feature, but I think an `.prisma-case-format` file could be a reasonable introduction:

```YAML
# alternative to specifying cmd line args
defaults:
  table: pascal,plural
  field: camel
  enum:  pascal
  mapTable: snake
  mapField: snake
  mapEnum:  snake
uses_next_auth: true # optional: apply default conventions for "next-auth" models
overrides:
  ModelX:
    defaults: # specify overridden defaults for this scope
      table: snake,singular
      mapTable: pascal
    fields: # apply element-wise overrides
      # alternate short-hand; note this works in model-wise defaults & global defaults
      userId: field=pascal;mapField=pascal,plural
  other_model: disable # shut it off entirely  
```

**Comment by iiian** [comment]
Okay, so I ended up not going for the `//prisma-case-format:disable` comments at all, since its manageable from the `.prisma-case-format` file.

The next PR will contain updates for the `README.md`, but here's an example of the syntax:

```yaml
# file: .prisma-case-format
uses_next_auth: false
default: ...
overrides:
  Account:
    default: 'table=pascal; mapTable=pascal;'
    field:
      id:                'field=camel; mapField=camel'
      userId:            'field=camel; mapField=camel'
      type:              'field=camel; mapField=camel'
      provider:          'field=camel; mapField=camel'
      providerAccountId: 'field=camel; mapField=camel'
      refresh_token:     'field=snake; mapField=snake'
      access_token:      'field=snake; mapField=snake'
      expires_at:        'field=snake; mapField=snake'
      token_type:        'field=snake; mapField=snake'
      scope:             'field=snake; mapField=snake'
      id_token:          'field=snake; mapField=snake'
      session_state:     'field=snake; mapField=snake'
      user:              'field=snake; mapField=snake'
  Session:
    default: 'table=pascal; mapTable=pascal; field=camel; mapField=camel'
  User:
    default: 'table=pascal; mapTable=pascal; field=camel; mapField=camel'
  VerificationToken:
    default: 'table=pascal; mapTable=pascal; field=camel; mapField=camel'
```

note that the above example is strictly equivalent to 

```yaml
# file: .prisma-case-format
uses_next_auth: true
```

or to specifying the commandline argument `--uses-next-auth`.
