### ISSUE TITLE
Add option to ignore pluralize option per field

### ISSUE THREAD

**Issue by antonioorct** [iiian/prisma-case-format#52]
Original model:
```
model Model {
  id               String   @id @default(cuid())
  columnsSingular  String[]
}
```

After running `prisma-case-format -p`:
```
model Model {
  id                String     @id @default(cuid())
  columnsSingulars  String[]   @map("columns_singulars")
}
```

The only way to prevent this is by adding the following to `.prisma-case-format`:
```yaml
Model:
    field:
      columnsSingular: disable
```

But this disables all formatting on the following field as I'd like to keep the option of mapping e.g. camel case to snake case.

Something like this would be great:
```yaml
Model:
    field:
      columnsSingular: 'pluralize=disable'
```

**Comment by iiian** [comment]
I swear this is possible today, let me look through the code for a moment and get back to you but if it's not possible then yes I agree let's support this

**Comment by iiian** [comment]
@antonioorct I have two solutions that you might explore:

### 1: using `!`

```yaml
Model:
  field:
    columnsSingular: 'mapField=!columns_singular'
```

The exclamation point tells the `mapField` to "use this exact value".

### 2: using `,singular`

```yaml
Model:
  field:
    columnsSingular: 'mapField=snake,singular'
```

This says "use snakecase with a **singular** plurality convention when trying to map this field"

This works, because case-convention syntax is always:

```
(snake|pascal|camel)[,(singular|plural)]
```

Also, a `plural=disable` would probably be equivalent to specifying `,singular`

**Comment by iiian** [comment]
@antonioorct another thing you could do that would help me to help you is to clarify, explicitly, what your desired outcome is: right now, it's still a bit ambiguous and unclear which of the following you **want** to occur:

```prisma
columnsSingular   String[]   @map("columns_singular")     // both field & mapField singular
columnsSingulars  String[]   @map("columns_singular")     // mapField singular
columnsSingular   String[]   @map("columns_singulars")    // field singular
```

**Comment by antonioorct** [comment]
I'm running `prisma-case-format --pluralize` because I want to pluralize array fields, but I have a field I want ignored.
I've tried both of your solution and neither of them worked and I've also tried various combinations of `field`, `mapField` and similar with also explicit naming `!` and that also didn't work.  
Essentially I want the `field` name to be forced to singular

I want the following to be the final output:
```prisma
columnsSingular   String[]   @map("columns_singular")
```

**Comment by antonioorct** [comment]
https://github.com/antonioorct/prisma-case-format-test

I've created a reproducible example in this repository:
```
npm install
npm run format-prisma
```

I've set `field=camel,singular` but running with `--pluralize` ignores that, sets the field to be plural but the mapped field remains singular.

**Comment by iiian** [comment]
Okay, I'll be able to get to this issue by Tuesday next week at the earliest. I think you're probably right that this is broken slash an oversight in needed functionality

**Comment by iiian** [comment]
Hey @antonioorct, please install `prisma-case-format@2.2.1-beta.0` and give it a test. You should be able to do any of the following `columnsSingular` paradigms:

```yaml
default: 'field=camel; table=pascal; enum=pascal; pluralize=true'
override:
  Model:
    field:
      columnsSingular: 'mapField=snake,singular'
      columnsSingular: 'mapField=snake; pluralize=disable'
      columnsSingular: 'mapField=!columns_singular' # this will preserve pluralization
```

Additionally, you can now specify `-p` at the command line or embed it in the config file. Up to you.
